### ISSUE TITLE
Can't link openssl on Linux

### ISSUE THREAD

**Issue by skyweb07** [vapor/ctls#2]
hi guys, I'm wondering if you test the linking of this on Linux because i can't make it work, this is a reference link for that https://github.com/vapor/vapor/issues/954#issuecomment-292486517, thanks!

**Comment by tanner0101** [comment]
yes, we test on linux. we don't test on Heroku however and we have no official buildpacks for Vapor 2 yet.

https://github.com/vapor/tls/blob/master/circle.yml
https://circleci.com/gh/vapor/tls

(closing this in favor of the first issue named "Unable to deploy Vapor 2.0 beta in Heroku")
