### ISSUE TITLE
CTLS warning on Heroku

### ISSUE THREAD

**Issue by JrGoodle** [vapor/ctls#6]
I've been consistently getting a warning related to pkg-config on Heroku when building a Vapor app. The app works fine, but I always get this warning when building:

```
warning: error while trying to use pkgConfig flags for CTLS: couldNotFindConfigFile
```

I mentioned this on the Swift mailing list, and here was a response:

> Assuming ctls is this: https://github.com/vapor/ctls, then this warning is because ctls has a pkgConfig directive that says “ctls”, but there is no ctls.pc file on the system. That’s hardly a surprise, given that ctls is a pure Swift package.

> Step 1 in fixing this would be to get ctls change their .pc file from macos.pc to ctls.pc, but I don’t think that’s enough because the .pc file would still not be on the PKG_CONFIG_PATH. I don’t think the .pc file in ctls works at all, and they should just remove it and have the pkgConfig directive call for “openssl” instead. That will work fine with Homebrew and will achieve the result they’re looking for.

See https://lists.swift.org/pipermail/swift-build-dev/Week-of-Mon-20171127/001101.html

**Comment by 0xTim** [comment]
@JrGoodle you can safely ignore that warning - it won't cause any issues on Linux. If you want to get rid of it, you need to install the CTLS package from the Vapor APT repo but I would just ignore this

**Comment by vzsg** [comment]
The ctls pkg-config file was created to work around issues with how brew manages the openssl installation on macOS. It's completely irrelevant on Linux – the build process will pick up `libssl-dev` just fine. This will all go away in v3, by the way.

**Comment by JrGoodle** [comment]
ok, cool. thanks for the feedback, I'll close the issue
